name: 'Push to main'

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Reboot API
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./yanbf-reboot.sh
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PRIVATE_KEY}}
